name: Update HCB Data
on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:

jobs:
  build-data:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pdfplumber python-dateutil rapidfuzz
      - name: Run pipeline
        run: python scripts/update_data.py
      - name: Commit if data changed
        run: |
          if [[ -n "$(git status --porcelain data/index.json)" ]]; then
            git config user.name "halalintel-bot"
            git config user.email "bot@users.noreply.github.com"
            git add data/index.json
            git commit -m "data: refresh $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push
          else
            echo "No changes to commit."
          fi
